# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSBuildApp' do
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  pod 'appcenter', path: '../node_modules/appcenter'
pod 'appcenter-analytics', path: '../node_modules/appcenter-analytics'
pod 'appcenter-crashes', path: '../node_modules/appcenter-crashes'
pod 'appcenter-push', path: '../node_modules/appcenter-push'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSBuildApp

  

  platform :ios, '9.0'
  target 'iOSBuildAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'iOSBuildApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSBuildApp-tvOS

  target 'iOSBuildApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
